# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ modulesPath, pkgs, ... }:

{
  imports = [
    # Include the default incus configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    ./incus.nix
    ./modules/freeswitch.nix
  ];

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };
  nixpkgs.config.permittedInsecurePackages = [
    "openssl-1.1.1w"
  ];
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    max-jobs = "auto";
    cores = 0;
  };
  disabledModules = [ "services/misc/freeswitch.nix" ];
  services.freeswitch = {
    enable = true;

    # REMOVE OR COMMENT THIS LINE:
    # configDir = ./fs-conf;

    sipTcpPorts = [ 5060 ];
    sipUdpPorts = [ 5060 ];
    rtpStartPort = 20000;
    rtpEndPort = 21000;

    vars = {
      domain = "192.168.2.56";
      default_password = "SecurePassword123!";
      internal_sip_port = "5060";
      rtp_start_port = "20000";
      rtp_end_port = "21000";
    };

    directory = {
      "default" = {
        "1000" = {
          password = "PhonePassword123";
          context = "default";
        };
      };
    };

    dialplan = {
      "default" = {
        "local_extension" = {
          conditions = [
            {
              field = "destination_number";
              expression = "^(1000)$";
              actions = [
                { app = "bridge"; data = "user/$1"; }
              ];
            }
          ];
        };
      };
    };
  };
  # ---------------------------------------------------------
  # CONVENIENCE ALIASES
  # ---------------------------------------------------------
  programs.bash = {
    enable = true;
    shellAliases = {
      ll = "ls -lahvF --color=tty";
      rr = "sudo nixos-rebuild switch";
      cc = "sudo vim /etc/nixos/configuration.nix";
      # Check if BTRFS NOCOW is active on reth dir
      check-cow = "lsattr -d /var/lib/reth";
    };
  };
  environment.systemPackages = with pkgs; [
    e2fsprogs       # REQUIRED: contains 'chattr' command for btrfs
    vim
    vim-vint
    vimPlugins.vim-nix
    btop
    openssl
    curl
    jq
    git
    gh
    ripgrep
  ];
  environment.interactiveShellInit = ''
    export PS1="\\[\\e[0;32m\\][ \$? \\[\\e[0;33m\\]\\t \\[\\e[0;32m\\]\\u \\[\\e[0;33m\\]\\w \\[\\e[0;32m\\]] \\$ \\[\\e[0m\\]"
  '';

  system.stateVersion = "26.05"; # Did you read the comment?
}
